[opencvcamera]
framerate = 30.0
resolution = [ 1280, 720,]
bufferpath = "buffer/buffer.h5"

[edgedetection]
subpixelscheme = "Linear"

[sessiledrop]
defaultfitpixels = 40
fittype = "Polyfit"
polyfitorder = 2
